name: hermes_ai_market_analysis
version: 0.1.0
publish_to: 'none'
description: AI-powered market analysis app with real-time signals

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  fl_chart: ^0.65.0
  provider: ^6.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  
  # WebSocket for real-time data
  web_socket_channel: ^3.0.0
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # UI components
  material_symbols_icons: ^4.2785.1
  
  # Loading indicators
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
