version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hermes_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hermes_dev
      - BINANCE_KEY=${BINANCE_KEY}
      - ALPHAVANTAGE_KEY=${ALPHAVANTAGE_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - '6379:6379'

volumes:
  postgres_data:
