services:
  - type: web_service
    name: hermes-backend
    env: docker
    branch: master
    plan: starter
    rootDir: .
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    startCommand: "python backend/run_app.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
    healthCheckPath: /health
