# Minimal stub for lightgbm used by the project
from typing import Any, Dict, Optional

class Dataset: ...

class Booster:
    def predict(self, data: Any) -> Any: ...


def early_stopping(num_rounds: int) -> Any: ...
def log_evaluation(period: int) -> Any: ...

def train(params: Dict[str, Any], train_set: Dataset, num_boost_round: int = ..., valid_sets: Optional[list] = ...) -> Booster: ...

