from typing import Any, Tuple

# Single declarations for commonly used talib functions
def RSI(values: Any, timeperiod: int = ...) -> Any: ...
def MACD(values: Any, fastperiod: int = ..., slowperiod: int = ..., signalperiod: int = ...) -> Tuple[Any, Any, Any]: ...
def BBANDS(values: Any, timeperiod: int = ..., nbdevup: int = ..., nbdevdn: int = ...) -> Tuple[Any, Any, Any]: ...
def STOCH(high: Any, low: Any, close: Any, k_period: int = ..., d_period: int = ...) -> Tuple[Any, Any]: ...
def WILLR(high: Any, low: Any, close: Any, timeperiod: int = ...) -> Any: ...
def OBV(close: Any, volume: Any) -> Any: ...
def TRANGE(high: Any, low: Any, close: Any) -> Any: ...

# Optional / less-common functions
def ADX(high: Any, low: Any, close: Any, timeperiod: int = ...) -> Any: ...
def CCI(high: Any, low: Any, close: Any, timeperiod: int = ...) -> Any: ...
def AD(high: Any, low: Any, close: Any, volume: Any) -> Any: ...
def MOM(values: Any, timeperiod: int = ...) -> Any: ...
def ROC(values: Any, timeperiod: int = ...) -> Any: ...
