version: '3.8'
services:
  hermes-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - ALPHAVANTAGE_KEY=${ALPHAVANTAGE_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
