// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // For web builds, return a dummy config without initializing Firebase
      // This app is designed for mobile/desktop only
      throw UnsupportedError(
        'This app is designed for iOS, Android, and macOS only. '
        'Web support is not available.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'This app supports iOS, Android, and macOS only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVu_7-TPg2RaBoh9AyTTP17SgJaKPTaI',
    appId: '1:720939750473:android:28151b1caae31265439b98',
    messagingSenderId: '720939750473',
    projectId: 'hermes-872d2',
    storageBucket: 'hermes-872d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDVu_7-TPg2RaBoh9AyTTP17SgJaKPTaI',
    appId: '1:720939750473:ios:6e6b7c8e7f5d6c8d439b98',
    messagingSenderId: '720939750473',
    projectId: 'hermes-872d2',
    storageBucket: 'hermes-872d2.firebasestorage.app',
    iosBundleId: 'com.example.hermesAiMarketAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDVu_7-TPg2RaBoh9AyTTP17SgJaKPTaI',
    appId: '1:720939750473:ios:6e6b7c8e7f5d6c8d439b98',
    messagingSenderId: '720939750473',
    projectId: 'hermes-872d2',
    storageBucket: 'hermes-872d2.firebasestorage.app',
    iosBundleId: 'com.example.hermesAiMarketAnalysis',
  );
}
